version: '3.3'
services:
  mongo:
    image: 'mongo:latest'
    container_name: 'mongodb'
    ports:
      - '27017:27017'

  app:
    container_name: app
    build: .
    ports:
      - 8080:8080
    depends_on:
      - mongo