basePath: /
definitions:
  github_com_Sayanli_TestTaskBackDev_internal_domain.Token:
    properties:
      accesstoken:
        type: string
      refreshtoken:
        type: string
    type: object
  github_com_Sayanli_TestTaskBackDev_internal_domain.User:
    properties:
      guid:
        type: string
      refreshtoken:
        type: string
    type: object
  internal_controller_http_handler.CreateUser:
    properties:
      guid:
        type: string
    type: object
host: 127.0.0.1:8080
info:
  contact: {}
  description: This is auth service
  title: Auth service API
  version: "1.0"
paths:
  /api/v1/auth/create:
    post:
      consumes:
      - application/json
      description: Create user
      parameters:
      - description: create user
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/internal_controller_http_handler.CreateUser'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Sayanli_TestTaskBackDev_internal_domain.Token'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Create user
      tags:
      - auth
  /api/v1/auth/refresh:
    post:
      consumes:
      - application/json
      description: Refresh token
      parameters:
      - description: refresh tokens
        in: body
        name: input
        required: true
        schema:
          $ref: '#/definitions/github_com_Sayanli_TestTaskBackDev_internal_domain.User'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/github_com_Sayanli_TestTaskBackDev_internal_domain.Token'
        "500":
          description: Internal Server Error
          schema: {}
      summary: Refresh token
      tags:
      - auth
swagger: "2.0"
